name: PR Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [develop]
    paths:
      - "force-app/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Salesforce CLI + Scanner
        run: |
          npm install @salesforce/cli -g
          sf --version
          sf plugins install @salesforce/sfdx-scanner
          sf plugins install sfdx-git-delta

      - name: Run Code Formatting Check
        run: npm run prettier:verify

      - name: Run ESLint
        run: npm run lint

      - name: Create delta package for validation
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "origin/develop" --output changed-sources/ --generate-delta --source force-app/

      - name: Run SFDX Scanner on changed files
        run: |
          if [ -d "changed-sources/force-app" ]; then
            sf scanner run --format sarif --target './changed-sources/force-app/**/*.cls,./changed-sources/force-app/**/*.trigger' \
              --category "Design,Best Practices,Performance,Security" \
              --outfile 'apexScanResults.sarif' \
              --severity-threshold 3
            echo "SARIF_EXISTS=true" >> $GITHUB_ENV
          else
            echo "No Apex classes or triggers to scan"
            echo "SARIF_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Upload SARIF file for GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: env.SARIF_EXISTS == 'true'
        with:
          sarif_file: apexScanResults.sarif

      - name: Authenticate to UAT Org
        run: |
          echo "${{ secrets.SF_UAT_AUTH_URL }}" > ./authfile.txt
          sf org login sfdx-url --sfdx-url-file ./authfile.txt --alias uatorg

      - name: Validate deployment to UAT (dry-run)
        run: |
          if [ -d "changed-sources/force-app" ]; then
            sf project deploy start --source-dir ./changed-sources/force-app \
              --target-org uatorg \
              --dry-run \
              --test-level RunLocalTests \
              --verbose
          else
            echo "No changes to validate"
          fi

      - name: Clean up auth file
        if: always()
        run: rm -f ./authfile.txt
